epc <- read.table("household_power_consumption.txt",sep=";", header = TRUE)
epc$DateTime <- strptime(paste(epc$Date, epc$Time), format="%d/%m/%Y %H:%M:%S")
epc$Date <- as.Date(as.character(epc$Date),format="%d/%m/%Y")
epca <- subset(epc, Date == as.Date("2007-02-01")|Date == as.Date("2007-02-02"))
epca$Global_active_power <- as.numeric(as.character(epca$Global_active_power))
png(filename = "plot2.png",width = 480, height = 480, units = "px")
plot(epca$DateTime,epca$Global_active_power,type="l",xlab ="", ylab = "Global Active Power (kilowatts)",xaxt="n")
r <- as.POSIXct(round(range(epca$DateTime), "days"))
axis.POSIXct(1, at=seq(r[1], r[2], by="day"), label=c("Thu","Fri","Sat"))
dev.off()

