epc <- read.table("household_power_consumption.txt",sep=";", header = TRUE)
epc$DateTime <- strptime(paste(epc$Date, epc$Time), format="%d/%m/%Y %H:%M:%S")
epc$Date <- as.Date(as.character(epc$Date),format="%d/%m/%Y")
epca <- subset(epc, Date == as.Date("2007-02-01")|Date == as.Date("2007-02-02"))
epca$Sub_metering_1 <- as.numeric(as.character(epca$Sub_metering_1))
epca$Sub_metering_2 <- as.numeric(as.character(epca$Sub_metering_2))
epca$Sub_metering_3 <- as.numeric(as.character(epca$Sub_metering_3))
png(filename = "plot3.png",width = 480, height = 480, units = "px")
plot(epca$DateTime,epca$Sub_metering_1,type="l",xlab ="", ylab = "Energy Sub Metering",xaxt="n")
lines(epca$DateTime,epca$Sub_metering_2,col="red")
lines(epca$DateTime,epca$Sub_metering_3,col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"))
r <- as.POSIXct(round(range(epca$DateTime), "days"))
axis.POSIXct(1, at=seq(r[1], r[2], by="day"), label=c("Thu","Fri","Sat"))
dev.off()
