epc <- read.table("household_power_consumption.txt",sep=";", header = TRUE)
epc$DateTime <- strptime(paste(epc$Date, epc$Time), format="%d/%m/%Y %H:%M:%S")
epc$Date <- as.Date(as.character(epc$Date),format="%d/%m/%Y")
epca <- subset(epc, Date == as.Date("2007-02-01")|Date == as.Date("2007-02-02"))
epca$Global_active_power <- as.numeric(as.character(epca$Global_active_power))
epca$Sub_metering_1 <- as.numeric(as.character(epca$Sub_metering_1))
epca$Sub_metering_2 <- as.numeric(as.character(epca$Sub_metering_2))
epca$Sub_metering_3 <- as.numeric(as.character(epca$Sub_metering_3))
epca$Voltage <- as.numeric(as.character(epca$Voltage))
epca$Global_reactive_power<- as.numeric(as.character(epca$Global_reactive_power))
png(filename = "plot4.png",width = 480, height = 480, units = "px")
par(mfrow=c(2,2))
plot(epca$DateTime,epca$Global_active_power,type="l",xlab ="", ylab = "Global Active Power",xaxt="n")
r <- as.POSIXct(round(range(epca$DateTime), "days"))
axis.POSIXct(1, at=seq(r[1], r[2], by="day"), label=c("Thu","Fri","Sat"))
plot(epca$DateTime,epca$Voltage,type="l",xlab ="datetime", ylab = "Voltage",xaxt="n")
axis.POSIXct(1, at=seq(r[1], r[2], by="day"), label=c("Thu","Fri","Sat"))
plot(epca$DateTime,epca$Sub_metering_1,type="l",xlab ="", ylab = "Energy Sub Metering",xaxt="n")
lines(epca$DateTime,epca$Sub_metering_2,col="red")
lines(epca$DateTime,epca$Sub_metering_3,col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"),bty="n")
axis.POSIXct(1, at=seq(r[1], r[2], by="day"), label=c("Thu","Fri","Sat"))
plot(epca$DateTime,epca$Global_reactive_power,type="l",xlab ="datetime", ylab = "Globa_rective_power",xaxt="n")
axis.POSIXct(1, at=seq(r[1], r[2], by="day"), label=c("Thu","Fri","Sat"))
dev.off()

